services:
  - type: web
    name: management-flota-auto
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /tmp/data
      sizeGB: 1